# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source "https://github.com/CocoaPods/Specs.git"

inhibit_all_warnings!  # 关闭所有警告

target 'MBCoder' do
#  use_frameworks!

  pod 'FMDB'
  pod 'FMDB/FTS'
  pod 'FMDB/SQLCipher'
  
  pod 'Protobuf'
  pod 'libextobjc'
  pod 'YogaKit'
  pod 'PromiseKit'
  pod 'PromiseKit/Foundation'
  pod 'PromiseKit/UIKit'
  pod 'lottie-ios', '~> 2.5.3'
  pod 'SVGAPlayer', '~> 2.3.5'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'VasSonic'
  pod 'HybridPageKit'
  pod 'YYKit'
  pod 'FDFullscreenPopGesture'
  pod 'TZScrollViewPopGesture' # 和FDFullscreenPopGesture库不冲突
  pod 'KVOController'
  pod 'MMKV'
  pod 'GPUImage'
  pod 'FBMemoryProfiler'
  pod 'MLeaksFinder'
  
  target 'MBCoderUITests' do
    inherit! :search_paths
    pod 'Kiwi'
  end

end
