# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'IBCoder1' do

  pod 'FMDB/FTS' 
  pod 'FMDB/SQLCipher'
  pod 'Protobuf'
  pod 'libextobjc', '~> 0.6'
#  pod 'YogaKit', '~> 1.14.0'
#  pod 'PromiseKit', '~> 6.11.0'
#  pod 'PromiseKit/Foundation'
#  pod 'PromiseKit/UIKit'
#  pod 'lottie-ios', '~> 2.5.3'
#  pod 'Kiwi', '~> 3.0.0'

end
